language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- sh run_tests.sh
branches:
  only:
  - master
deploy:
  provider: pypi
  user: keotl
  password:
    secure: pv1AkPiENtJrT4YuWiqTHcHbqbL0Re0bn7S7NdV6tutSl7BV3kmSAVe+iGkXvwS6MDykygmdStgoYUtQubk5Tohwxz/Ow8ZvfAmsZiC2nlbXAbuJv/m1vqlE+YSY/Hx4DjZWqdqz5fxHWZxo0Ce6pcDWUiXfyvpt3jZaIZzGft2GO1OcYA9IgNAjKATUOXI7kLHUTMKIH4mVyeE4KPRgF/nz5XVnMGro6hHKvSD37eRreBKZbuwp9VMVNestbPYBPm82iLSeIVsrgetFpHR2DUhHfx0XksrUiDLcAqK0nXBjvqbne29AUN2BSY4jA7QhImrKggAaLYiLzIOWrfuDv9URyY2tYaABOpmqnZNEgK+2PJmgz5lqWWAgnurzGpGorm7Ch9MQuneGvL3mVf5e7dLyfJshPbb/F4yXg1GFIFbNAtfyvhBbxxZlEp9tkjvOJVG/NLnZEg3QCS+/ruDZbRh/mDby7bI3kW+74tQyb25EM3TJkfKWJBCy5eFhuYRnFxb/owsmh7roaOzWxmTbpLLCpp46dFHbP913X5KK/nnxEaiyLvgI40n/xlknBCmao5fwKAKJc4DUNZ/Mpyl9M4gISrFSzeXfs/4K/9G+ep6t9OQMSakqoMBmOkFG+D/hDLkHZtPJVmYnVUXY0oWrK6fql2/yLa3BMQJPI9778Gc=
  on:
    tags: true
