language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- sh run_tests.sh
branches:
  only:
  - master
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  provider: pypi
  user: keotl
  password:
    secure: "A6enYqr3QztFYO89qmVLstkUz6jaRHCcXLjRge1ieAQ7Er45coIAt7Z3u6itNg7Qdo8IU9x6kUvmBfNGjIu/1OWmRFbD3G4KXxGrqGcSfTa7CIpLKw/U3vNcdgGfuIdBbsDYgLMhpL8xMXLoFsbrNbinKU2REOjfF7UoT1OfSDMxnkjgm6Cqb+rNBA9XRUV7vm5/yHA4QEWYIjvs6sUUM6w0rm/6OtxkwPzW8iJGw9kD8KtKAT3y+r64htd5lidptSzRAkWTOXDBlOSi5ZoYeSLckDyJnv12OtLzqOk7PpbKYfAinzBtwtSyJ/ewsrFSUaAB2hDfXHWkTznQYSHAWAJPP5LtuSn3LH8xWtx42vXlsjUGwJbZuBOxg420BpzZ30hD4HorkU6GLhi4JxAdbyeSLSnsyTYdjpR0OZBZntBandJAx5fKzXhQ9sR8k5HvBM+Hv9QnaGmsR7wAW4l/7PiHPz+TCS/P1FqO+sKL6bSkAtMeKjpStDY3IMyaLEOvl/VHskUvDRnot8laiLQ7w0HQgifqN7vnlDPGuRc2hr/LgQQFiwdB2mGdPar+ENMHB14TIY3WeV3DlK70T+UvvwbevZnj21IvFrvES1eUrjIJl40wg2NGeRpFK7pjfSefDua7LUc6eFGpri/haIfwj3KsKc3ZwW8X4wnJ2QzHeCw="
  on:
    tags: true
    repo: keotl/jivago
