language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- sh run_tests.sh
branches:
  only:
  - master
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  provider: pypi
  user: keotl
  password:
    secure: BE/aAeByStNR4vPFeqUsZaetZ0t/FcyIxGsD2WX43LDmVzoGb20yUypHUsB2IF8Dujsx2xm9wYkT6xpuN244qesUJuW2IcjPo/ifVKka6YcAcuRUuck0lwK9enTR87lcC66Q3aEUBhibaW6rFota3Wc62ySruLj4O9i6b5crSe43GoxmE47R3wavJvEepL21APYuzIRbHOspZYB/PsvWzBacWd3NRKi5MyaLQbo8FKqYD34z4m22aAqxMkVz1Z4gwbFw5MA/msMakZ/lMaWCAnpqFlq3Xd7iF+ZMwIweTWIQVdQ8g1B6fv2mieJF8EZQF7valyD7OKizUJ/5e0RBo8A8ihL7iG0DikcpWc+rk2U9/a3CXYUk6LRD3an/c2r8HnQo0cJt0RSIqy8/0TV/M0UOMYCI0lpb/vWVIzB2nhNCtAJv7lZAcbKk2Eq6M7h5yu227o/ReItp7QX2qyodqNNwj6j29S72cz41S8DSw1O/Fnoe5fPyfvc5F7c2uDpHtVYaqpGVnyPbTiOYxzNFA0ucboGnWQf+fIfAxrr247mSOfumnr36bxvp//G6V1d/RN4UGhBzBd+qjmTcI8qQe7njWbon8P2L+pqrUhCfk0YW2F6Vd3DhJJPy2pS6vzf+1jVhDsEqQgatVB7v5UWxE3u3mbuf8jGvJWByyfTQiQU=
  on:
    tags: true
    repo: keotl/jivago
